version: "3.8"

services:
  app:
    build: .
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - ./package.json:/app/package.json
      - /app/node_modules
    environment:
      REACT_APP_VERSION: ${REACT_APP_VERSION}
      REACT_APP_MAPBOX_ACCESS_TOKEN_PUBLIC: ${REACT_APP_MAPBOX_ACCESS_TOKEN_PUBLIC}
      REACT_APP_MAPBOX_ACCESS_TOKEN: ${REACT_APP_MAPBOX_ACCESS_TOKEN}
    networks:
      - climbing-map
      - bapmarty

networks:
  climbing-map:
    name: cm
  bapmarty:
    name: bapmarty
